kind: pipeline
name: default
steps:
  - name: tags
    image: alpine:3.14
    commands:
      - echo -n "latest,${DRONE_TAG}" > .tags

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: lynqtech/docker-kustomize

trigger:
  event:
    - tag